# Tarea día 8
**Programación I**

In [3]:
import numpy as np

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [115]:
ceros = np.zeros(100)
ceros[0:50]=1

print(ceros)
print(ceros.sum())
np.random.shuffle(ceros)
unos = ceros.reshape(10,10)
print(unos)
print(unos.sum())

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
50.0
[[0. 0. 1. 1. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 1. 1. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1. 0. 1. 0. 0.]]
50.0


In [163]:
filas=3
columnas=4
x = np.zeros(filas*columnas)
j = np.arange(filas*columnas)
i = np.random.choice(j,int(filas*columnas/2),replace=False)
x[i]=1
x.reshape((filas,columnas))

array([[1., 0., 0., 0.],
       [1., 0., 1., 1.],
       [0., 1., 0., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



In [129]:
new_ceros = np.zeros([5,2])
new_unos = np.ones([5,2])
print(new_ceros)
print(new_unos)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [127]:
columna_ceros = new_ceros.reshape(10,1)
columna_unos = new_unos.reshape(10,1)
print(columna_ceros)
print(columna_unos)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [293]:
col_conca = np.concatenate((columna_ceros[None,:], columna_unos[None,:] ), axis=2)
print(col_conca)

[[[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]]


In [294]:
col_conca.ndim

3

In [151]:
filas_ceros = new_ceros.reshape(1,10)
filas_unos = new_unos.reshape(1,10)
filas_conca = np.concatenate((filas_ceros[None,:],filas_unos[None,:]))
print(filas_conca)
filas_conca.ndim

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]


3

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser un vector columna. 

In [242]:
x = np.random.random((10,1))*10
y = np.random.random((10,1))*10
z = np.random.random((10,1))*10


In [243]:
def f(x,y,z):    
    return 2*x + 3* y + np.sqrt(z)

In [244]:
print(f(x,y,z))
print(f(x,y,z).shape)

[[19.1298055 ]
 [40.15173268]
 [ 6.65200835]
 [21.17899893]
 [13.08421254]
 [ 8.42663981]
 [14.47220212]
 [16.27928549]
 [22.73781002]
 [36.8730546 ]]
(10, 1)


## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

Se hace el caso con el cuadrado en la esquina.

In [7]:
cuadrado50 = np.random.randint(0,2,size=(50,50))
print(cuadrado50)

cuadrado20 = cuadrado50[30:,0:20]

print(50*50*sum(sum(cuadrado20))/sum(sum(cuadrado50)))

[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 0 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 1]
 [1 0 0 ... 1 0 1]
 [1 0 0 ... 0 1 1]]
397.2332015810277


Se hace el caso con el cuadrado 

In [18]:
cuadrado5 = np.random.randint(0,2,size=(50,50))
print(cuadrado5)

cuadrado2 = cuadrado5[15:35,15:35]

print(50*50*sum(sum(cuadrado2))/sum(sum(cuadrado5)))

[[1 0 1 ... 1 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 1 ... 1 1 0]
 [1 1 0 ... 0 1 0]
 [1 1 0 ... 0 1 1]]
402.2526146419952


## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    


In [266]:
empty = np.empty([3,3])
empty
# 1 crea un arreglo de la dimensión indicada con valores vacíos

array([[4.94065646e-324, 2.12199579e-314, 2.12199579e-314],
       [4.94065646e-324, 2.12199579e-314, 4.94065646e-324],
       [2.12199579e-314, 4.94065646e-324, 0.00000000e+000]])

In [267]:
full = np.full([2,2],5)
full
# 2 crea un arreglo de la dimensión indicada llena de los valores indicados

array([[5, 5],
       [5, 5]])

In [268]:
zeros = np.zeros([3,3])
zeros
# 3 crea un arreglo de la dimensión (shape) indicada llena de ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [269]:
ones = np.ones([5,5])
ones
# 4 crea un arreglo de la dimensión (shape) indicada llena de unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [280]:
e_like = np.empty_like(ones)
e_like
# 5 crea un arreglo igual al indicado con valores vacíos.
# numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None

array([[5.09278990e-313, 5.72938864e-313, 5.30498948e-313,
        5.09278990e-313, 4.45619116e-313],
       [5.51718906e-313, 4.66839074e-313, 4.88059032e-313,
        4.66839074e-313, 5.09278990e-313],
       [5.09278990e-313, 4.45619116e-313, 5.94158822e-313,
        6.15378780e-313, 5.51718906e-313],
       [6.15378780e-313, 5.30498948e-313, 4.88059032e-313,
        4.66839074e-313, 4.88059032e-313],
       [4.88059032e-313, 4.45619116e-313, 5.94158822e-313,
        4.45619116e-313, 5.30498948e-313]])

In [281]:
identidad = np.identity(5)
identidad
# 6 crea la matriz identidad de la cantidad indicada

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [283]:
eye = np.eye(3, k= 1, dtype=int)
eye
# 7 crea un arreglo 2D con unos en la diagonal y ceros en el resto
# el dato k mueve el índice de la diagonal
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [286]:
diag =  np.diag(full,k=1)
diag
# 8 Regresa la diagonal de un arreglo ya creado. K es el índice de la diagonal a tomar

array([5])

In [287]:
a = [1,2]
np.asarray(a)
# 9 Convierte una lista a un arreglo

array([1, 2])

In [288]:
np.asarray('Hola')

array('Hola', dtype='<U4')

In [291]:
a = [1,2]
b = [3,2]
np.asanyarray([a,b])
# 10 numpy.asanyarray(a, dtype=None, order=None)
# Convert the input to an ndarray, but pass ndarray subclasses through.


array([[1, 2],
       [3, 2]])

In [300]:
x = np.asanyarray([a,b])
m = np.asmatrix(x)
x[0,0] = 5
m
# 11 Interpreta la entrada como una matriz

matrix([[5, 2],
        [3, 2]])

In [301]:
np.fromfunction(lambda i, j: i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [302]:
np.fromfunction(lambda i, j: i + j, (3,3), dtype = int)
# 12 numpy.fromfunction(function, shape, *, dtype=<class 'float'>, **kwargs)[source]
# Construct an array by executing a function over each coordinate.
# The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [304]:
iterable = (x*x for x in range(7))
np.fromiter(iterable, float)
# 13 numpy.fromiter(iterable, dtype, count=-1)
# Create a new 1-dimensional array from an iterable object.

array([ 0.,  1.,  4.,  9., 16., 25., 36.])

In [305]:
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [306]:
np.fromstring('1,2', dtype=int, sep=',')
# 14 numpy.fromstring(string, dtype=float, count=-1, sep='')
# A new 1-D array initialized from text data in a string.

array([1, 2])

In [307]:
np.arange(7)
# 15 numpy.arange
# numpy.arange([start, ]stop, [step, ]dtype=None)

array([0, 1, 2, 3, 4, 5, 6])

In [308]:
np.linspace(3.0,5.0,10)
# 16 numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# Return evenly spaced numbers over a specified interval.

array([3.        , 3.22222222, 3.44444444, 3.66666667, 3.88888889,
       4.11111111, 4.33333333, 4.55555556, 4.77777778, 5.        ])

In [310]:
np.logspace(3.0,5.0,num=4)
# 17 numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# Return numbers spaced evenly on a log scale.

array([  1000.        ,   4641.58883361,  21544.34690032, 100000.        ])

In [312]:
np.geomspace(1.0,5.0,num=4)
# 18 numpy.geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)
# Return numbers spaced evenly on a log scale (a geometric progression).

array([1.        , 1.70997595, 2.92401774, 5.        ])

In [315]:
nx, ny = (3,2)
x = np.linspace(0,1,nx)
y = np.linspace(0,1,ny)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)
# 19 numpy.meshgrid(*xi, copy=True, sparse=False, indexing='xy')
# Return coordinate matrices from coordinate vectors.

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


In [317]:
np.mgrid[0:5,0:5]
# 20 crea matrices en 2D

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [326]:
x = np.arange(3).reshape((3,1))
np.diagflat(x)
# 21 numpy.diagflat(v, k=0)
# Create a two-dimensional array with the flattened input as a diagonal.

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [330]:
np.tri(3,5,1, dtype=int)
# 22 numpy.tri(N, M=None, k=0, dtype=<class 'float'>)
# An array with ones at and below the given diagonal and zeros elsewhere.

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [332]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1)
# 23 numpy.tril(m, k=0)
# Lower triangle of an array.
# Return a copy of an array with elements above the k-th diagonal zeroed.

array([[ 1,  2,  0],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [334]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],-1)
# 24 numpy.triu(m, k=0)
# Upper triangle of an array.

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [335]:
x = np.array([1,2,3,5])
N = 3
np.vander(x, N)
# 25 numpy.vander(x, N=None, increasing=False)
# Generate a Vandermonde matrix.

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [336]:
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')

In [337]:
np.bmat([[A, B],[C, D]])
# 26 numpy.bmat(obj, ldict=None, gdict=None)
# Build a matrix object from a string, nested sequence, or array.

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [341]:
# import the important module in python 
import numpy as np 
		
# make an array with numpy 
gfg = np.array([[1, 2, 3], [4, 5, 6]]) 
geeks = [[4, 5, 6], [7, 8, 9]] 
		
# applying numpy.copyto() method 
np.copyto(gfg, geeks) 

print(gfg) 
# 27 numpy.copyto(dst, src, casting='same_kind', where=True)
# Copies values from one array to another, broadcasting as necessary.


[[4 5 6]
 [7 8 9]]


In [343]:
np.shape(gfg)
# 28 Return the shape of an array

(2, 3)

In [348]:
a= np.arange(6).reshape(2,3)
a
# 29 numpy.reshape(a, newshape, order='C')
# Gives a new shape to an array without changing its data.


array([[0, 1, 2],
       [3, 4, 5]])

In [350]:
x = np.array([[1,2,3],[4,5,6]])
np.ravel(x)
# 30 numpy.ravel(a, order='C')[source]
# Return a contiguous flattened array.

array([1, 2, 3, 4, 5, 6])

In [352]:
x.flat[5]
# 31 ndarray.flat
# A 1-D iterator over the array.

6

In [353]:
a= np.arange(6).reshape(2,3)
a.flatten()
# 32 ndarray.flatten(order='C')
# Return a copy of the array collapsed into one dimension.

array([0, 1, 2, 3, 4, 5])

In [355]:
x = np.zeros((3,4,5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [356]:
np.moveaxis(x,0,-1).shape
# 33 numpy.moveaxis(a, source, destination)[source]
# Move axes of an array to new positions.

(4, 5, 3)

In [360]:
a = np.ones((3,4,5,6))
np.rollaxis(a,3,1).shape
# 34 numpy.rollaxis(a, axis, start=0)[source]
# Roll the specified axis backwards, until it lies in a given position.


(3, 6, 4, 5)

In [361]:
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)
# 35 numpy.swapaxes(a, axis1, axis2)[source]
# Interchange two axes of an array.

array([[1],
       [2],
       [3]])

In [362]:
x = np.array([[1.,2.],[3.,4.]])
x.T
# 36 ndarray.T
# Transpuesta array.

array([[1., 3.],
       [2., 4.]])

In [367]:
x = np.arange(4).reshape((2,2))
print(x)
np.transpose(x,axes=None)
# 37 Transpuesta a la que se le puede indicar que ejes cambiar entre sí

[[0 1]
 [2 3]]


array([[0, 2],
       [1, 3]])

In [380]:
x = np.arange(9.0).reshape(9)
np.atleast_1d(x)
# 38 numpy.atleast_1d(*arys)
# Convert inputs to arrays with at least one dimension.

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [379]:
x = np.arange(9.0).reshape(9)
np.atleast_2d(x)
# 39 numpy.atleast_2d(*arys)
# View inputs as arrays with at least two dimensions.

array([[0., 1., 2., 3., 4., 5., 6., 7., 8.]])

In [378]:
x = np.arange(9.0).reshape(9)
np.atleast_3d(x)
# 40 numpy.atleast_3d(*arys)
# View inputs as arrays with at least three dimensions.

array([[[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]])

In [382]:
x = np.array([[1],[2],[3]])
y = np.array([4,5,6])
x + y
# 41 class numpy.broadcast
# Produce an object that mimics broadcasting.

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [383]:
x = np.array([1,2,3])
np.broadcast_to(x, (3,3))
# 42 numpy.broadcast_to(array, shape, subok=False)[source]
# Broadcast an array to a new shape.


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [384]:
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x,y)
# 43 numpy.broadcast_arrays(*args, subok=False)
# Broadcast any number of arrays against each other.


[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

In [385]:
x = np.array([1,2])
x.shape

(2,)

In [391]:
y = np.expand_dims(x, axis=0)
y.shape
# equivalente al siguiente

(1, 2)

In [392]:
y = np.expand_dims(x, axis=1)
y.shape
# equivalente al anterior
# 44 numpy.expand_dims(a, axis)
# Expand the shape of an array.

(2, 1)

In [396]:
x = np.array([[[0],[1], [2]]])
x.shape

(1, 3, 1)

In [402]:
np.squeeze(x).shape
# 45 numpy.squeeze(a, axis=None)[source]
# Remove single-dimensional entries from the shape of an array.

(3,)

In [409]:
np.asscalar(np.array([24]))
# 46 numpy.asscalar(a)
# Convert an array of size 1 to its scalar equivalent.

24

In [410]:
x = np.arange(6).reshape(2,3)
x.flags
# 47 numpy.require(a, dtype=None, requirements=None)[source]
# Return an ndarray of the provided type that satisfies requirements.


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [411]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis=0)
# 48 numpy.concatenate((a1, a2, ...), axis=0, out=None)
# Join a sequence of arrays along an existing axis.


array([[1, 2],
       [3, 4],
       [5, 6]])

In [413]:
arrays = [np.random.randn(3,4) for _ in range(10)]
np.stack(arrays).shape
# 49 numpy.stack(arrays, axis=0, out=None)
# Join a sequence of arrays along a new axis.

(10, 3, 4)

In [414]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))
# 50 numpy.column_stack(tup)
# Stack 1-D arrays as columns into a 2-D array.

array([[1, 2],
       [2, 3],
       [3, 4]])

In [415]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))
# 51 numpy.dstack(tup)[source]
# Stack arrays in sequence depth wise (along third axis).

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [416]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))
# 52 numpy.hstack(tup)[source]
# Stack arrays in sequence horizontally (column wise).

array([1, 2, 3, 2, 3, 4])

In [417]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.vstack((a,b))
# 53 numpy.vstack(tup)[source]
# Stack arrays in sequence vertically (row wise).

array([[1, 2, 3],
       [2, 3, 4]])

In [419]:
A = np.eye(2) *2
B = np.eye(3) *3
np.block([[A,np.zeros((2,3))],[np.ones((3,2)),B]])
# 54 numpy.block(arrays)
# Assemble an nd-array from nested lists of blocks.


array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [420]:
x = np.arange(9.0)
np.split(x, 3)
# 55 numpy.split(ary, indices_or_sections, axis=0)[source]
# Split an array into multiple sub-arrays as views into ary.


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [421]:
x = np.arange(8.0)
np.array_split(x,3)
# 56 numpy.array_split(ary, indices_or_sections, axis=0)[source]
# Split an array into multiple sub-arrays.

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [422]:
x = np.arange(16.0).reshape(2,2,4)
np.dsplit(x,2)
# 57 numpy.dsplit(ary, indices_or_sections)[source]
# Split array into multiple sub-arrays along the 3rd axis (depth).

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [423]:
x = np.arange(16.0).reshape(4,4)
np.hsplit(x,2)
# 58 numpy.hsplit(ary, indices_or_sections)[source]
# Split an array into multiple sub-arrays horizontally (column-wise).

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [424]:
x = np.arange(16.0).reshape(4,4)
np.vsplit(x,2)
# 59 numpy.vsplit(ary, indices_or_sections)[source]
# Split an array into multiple sub-arrays vertically (row-wise).

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [425]:
a = np.array([0,1,2])
np.tile(a,2)
# 60 numpy.tile(A, reps)[source]
# Construct an array by repeating A the number of times given by reps.

array([0, 1, 2, 0, 1, 2])

In [426]:
np.repeat(3,4)
# 61 numpy.repeat(a, repeats, axis=None)[source]
# Repeat elements of an array.

array([3, 3, 3, 3])

In [427]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.delete(arr, 2,0)
# 62 numpy.delete(arr, obj, axis=None)
# Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [433]:
a = np.array([[1,1],[2,2],[3,3]])
np.insert(a,1,5,axis=1)
# 63 numpy.insert(arr, obj, values, axis=None)[source]
# Insert values along the given axis before the given indices.

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [436]:
np.append([[1,2,3],[4,5,6]],[[7,8,9]], axis=0)
# 64numpy.append(arr, values, axis=None)[source]
# Append values to the end of an array.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [437]:
A = np.arange(8).reshape((2,2,2))
print(A)
np.flip(A,0)
# 65 numpy.flip(m, axis=None)[source]
# Reverse the order of elements in an array along the given axis.

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [439]:
np.bitwise_and([15,13],17)
# 66 numpy.bitwise_and(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'bitwise_and'>
# Compute the bit-wise AND of two arrays element-wise.
# Computes the bit-wise AND of the underlying binary representation of the integers in the input arrays. This ufunc implements the C/Python operator &.

array([1, 1], dtype=int32)

In [442]:
np.bitwise_or(32,2)
# 67 numpy.bitwise_or(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'bitwise_or'>
# Compute the bit-wise OR of two arrays element-wise.
# Computes the bit-wise OR of the underlying binary representation of the integers in the input arrays. This ufunc implements the C/Python operator |.

34

In [443]:
np.binary_repr(54)
# 68 Return the binary representation of the input number as a string.

'110110'

In [445]:
x = np.invert(np.array(13, dtype=np.uint8))
x
# 69 numpy.invert(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'invert'>
# Compute bit-wise inversion, or bit-wise NOT, element-wise. 

242

In [452]:
x = np.array(["Hola ","Hola"])
y = np.array(["Diego.","DDD"])
np.char.add(x,y)
# 70 numpy.char.add(x1, x2)
# Return element-wise string concatenation for two arrays of str or unicode.
# Arrays x1 and x2 must have the same shape.

array(['Hola Diego.', 'HolaDDD'], dtype='<U11')

In [448]:
x = np.array("Hola ")
y = np.array("Diego.")
np.char.join(x,y)
# 71 numpy.char.join(sep, seq)
# Return a string which is the concatenation of the strings in the sequence seq.

array('DHola iHola eHola gHola oHola .', dtype='<U31')

In [449]:
c = np.array(['A1B C', '1BCA', 'BCA1'])
np.char.lower(c)
# 72 numpy.char.lower(a)
# Return an array with the elements converted to lowercase.
# Call str.lower element-wise.

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [451]:
C = np.array(['a1B c', '1b Ca', 'b Ca1', 'cA1b'])
np.char.swapcase(C)
# 73 numpy.char.swapcase(a)
# Return element-wise a copy of the string with uppercase characters converted to lowercase and vice versa.

array(['A1b C', '1B cA', 'B cA1', 'Ca1B'], dtype='<U5')

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    

In [456]:
a = np.random.random((5,5))
b = np.arange(1,15,3)

np.savez('Ejemplo_1', objA = a, objB = b)

In [458]:
d = np.load('Ejemplo_1.npz')

In [459]:
d['objA']

array([[0.18394607, 0.14861239, 0.18312851, 0.79946687, 0.03175579],
       [0.57751328, 0.01811324, 0.63901653, 0.07673359, 0.16285069],
       [0.92359356, 0.49296516, 0.09833661, 0.04332832, 0.10719932],
       [0.39805132, 0.83473833, 0.14666942, 0.69971155, 0.37022383],
       [0.95161564, 0.58078212, 0.69055002, 0.90454965, 0.20703708]])

In [461]:
A = np.arange(10)
np.save('Ejemplo_2', A)

e = np.load('Ejemplo_2.npy')
print(e)

[0 1 2 3 4 5 6 7 8 9]


3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    

In [470]:
a = np.random.random((5,5))
b = np.arange(1,15,3)
np.savetxt('Ejemplotxt',a,delimiter=',')

In [475]:
np.loadtxt('Ejemplotxt', delimiter=',')

array([[0.38202205, 0.69224576, 0.20994845, 0.59759332, 0.06568366],
       [0.86305708, 0.61414906, 0.49218205, 0.0044171 , 0.60984829],
       [0.55870677, 0.1639272 , 0.53756998, 0.26650975, 0.16436193],
       [0.1445622 , 0.17216569, 0.48610752, 0.03089566, 0.96855166],
       [0.52690429, 0.45888482, 0.40680135, 0.86724427, 0.21220552]])

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [4]:
def estimacionMCO(nombre):
    datos = np.genfromtxt(nombre,delimiter=',',skip_header=1)
    matriz_x = datos[:,:6]
    matriz_y = datos[:,6:7]
    XX = (matriz_x.T @ matriz_x)
    XY = (matriz_x.T @ matriz_y)
    Betas = (np.linalg.inv(XX) @ XY)
    return Betas

In [6]:
Betas = estimacionMCO('archivito.csv')
Betas

array([[-0.01262282],
       [ 0.42393696],
       [-0.00441209],
       [ 0.18619431],
       [ 0.33293596],
       [ 0.08798554]])